name: Send Anbox pulse reminders
on:
    schedule:
        - cron: "41 8 * * 1,2,3,5"

jobs:
    send-reminder:
        runs-on: ubuntu-latest
        steps:
            - name: Send Anbox pulse reminders
              env:
                WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
              run: |
                WEEK_NUM=`date +"%V"`
                WEEK_DAY_NUM=`date +%u"`
                
                function send_mattermost_msg() {
                  msg="$1"
                  curl -i -X POST \
                    -H 'Content-Type:application/json' \
                    -d "{\"text\": \"$msg\"}" \
                    "$WEBHOOK_URL"                
                }
                
                if [ $(($WEEK_NUM % 2)) -eq 1 ];  # First week of the pulse
                then
                  if [ $(($WEEK_DAY_NUM)) -eq 1 ];  # Monday
                  then
                    msg="@anbox-team Please publish pulse report as per [pulse duties rotation](https://docs.google.com/spreadsheets/d/1x8MOJXO1hy0uQmeKsTDGDmlOrpMh0XQp3LZf__ATJ3o)"
                    send_mattermost_msg "$msg"
                  fi
                else  # Second week of the pulse
                  if [ $(($WEEK_DAY_NUM)) -eq 2 ];  # Tuesday
                  then
                    msg="@anbox-team Please create pulse report as per [pulse duties rotation](https://docs.google.com/spreadsheets/d/1x8MOJXO1hy0uQmeKsTDGDmlOrpMh0XQp3LZf__ATJ3o)"
                    send_mattermost_msg "$msg"
                  fi
                  if [ $(($WEEK_DAY_NUM)) -eq 3 ];  # Wednesday
                  then
                    msg="@anbox-team Have you prepared for upcoming backlog grooming?\n- Create stories for anticipated work\n- Fill out description and acceptance criteria\n- Add priority, fix-version and sprint, if known"
                    send_mattermost_msg "$msg"
                  fi
                  if [ $(($WEEK_DAY_NUM)) -eq 5 ];  # Friday
                  then
                    msg="@anbox-team Have you prepared for upcoming sprint planning?\n- Create stories for any ad hoc work\n- Review the fix-version for your stories and if they are aligned with the target release\n- Account for time off\n- Assess if you have too much or too little work for the pulse"
                    send_mattermost_msg "$msg"
                    sleep 30
                    msg="@anbox-team Have you filled the pulse report?"
                    send_mattermost_msg "$msg"
                  fi
                fi

